// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzzxbkhnwuharijxzgqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6enhia2hud3VoYXJpanh6Z3FzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MzA2MjUsImV4cCI6MjA2ODEwNjYyNX0.-76a7me5_xYmfhae7umY4lP5HPBCJkrOnlEFJtDy65U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});